import type { Metadata } from 'next';
import { Exo_2 } from 'next/font/google';
import { Suspense } from 'react';

const exo2 = Exo_2({
  subsets: ['latin'],
  display: 'swap',
});

import './globals.css';

import Header from './_components/Header';
import Providers from './_providers/Providers';

export const metadata: Metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={`${exo2.className} dark m-4 md:m-8`}>
        <Suspense fallback={<>Loading...</>}>
          <Header />
        </Suspense>
        <Providers>
          <main className='mt-8'>{children}</main>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
